#! /bin/sh
set -uex

cd ./site

git init
git remote add origin https://github.com/yesq/yesq.github.io.git
git add . && git commit -m "init and force update blog" && git push --force --set-upstream origin master